### ISSUE TITLE
AttributeError: 'Axp192' object has no attribute 'setLDO2Vol'

### ISSUE THREAD

**Issue by masayoshikuroda** [rin-ofumi/m5stickc_wisun_hat#1]
test_WiSUN_Ambient.pyをUIFLow-1.4.2上で実行すると、以下のエラーが発生しました。

     AttributeError: 'Axp192' object has no attribute 'setLDO2Vol'

メソッド名をsetLDO2Volt  に変更すると実行できました。

**Comment by rin-ofumi** [comment]
UIFlow 1.4.2でメソッド名がsetLDO2Voltに変わっている部分を対策しました。
（下記を参考にさせて頂いております）
https://gist.github.com/ciniml/71788f7a741be224506f03e12bba861e

但し、UIFlow 1.4.2だとESP NOW同報で不具合がある様なので、推奨Verは1.4.1-betaとさせて頂いております。

**Comment by masayoshikuroda** [comment]
おそくなりました。確認しました。
